language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
# cache: cargo
rust:
  - nightly
env:
  - MANIFEST_PATH=Cargo.toml PersistenceType=Persistent LoadingType=Disk RUST_BACKTRACE=full RUST_LOG=veloci=trace FlushThreshold=20
  - MANIFEST_PATH=Cargo.toml PersistenceType=Persistent LoadingType=InMemory RUST_BACKTRACE=full RUST_LOG=veloci=trace
  - MANIFEST_PATH=Cargo.toml PersistenceType=Transient RUST_BACKTRACE=full RUST_LOG=veloci=trace
  - MANIFEST_PATH=buffered_index_writer/Cargo.toml
  - MANIFEST_PATH=parser/Cargo.toml
  - MANIFEST_PATH=doc_store/Cargo.toml
  - MANIFEST_PATH=server/Cargo.toml
  - MANIFEST_PATH=json_converter/Cargo.toml
script:
- cargo build --manifest-path=$MANIFEST_PATH
- cargo test --manifest-path=$MANIFEST_PATH

before_cache: |
  cargo install --git https://github.com/PSeitz/tarpaulin.git --branch develop --force

after_success: |
  # Uncomment the following line for coveralls.io
  RAYON_NUM_THREADS=1 cargo tarpaulin --manifest-path=$MANIFEST_PATH --all --exclude-files "src/bin/*" "benches/*" --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

  # Uncomment the following two lines create and upload a report for codecov.io
  RAYON_NUM_THREADS=1 cargo tarpaulin --manifest-path=$MANIFEST_PATH --all --exclude-files "src/bin/*" "benches/*" --out Xml
  bash <(curl -s https://codecov.io/bash)
